# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c13ce60138753314be4ef9b98f268347ba99f40ecc17d880e4d8b24784fc2fc30095b430bf2023afe9ebed538e1d04be5ae95335c5fab54103606628ab897be1

test:
  secret_key_base: 6f8c3a0d25c608255a4e2293313f9e1eb32c53925bd90dda54ce098076b3bb63bc9bc8d6074f409397fc362a89c7a01a521e4628c56f00db4bfddefa88349dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
